# Page settings

baseurl = "https://anjbapat.github.io/"
languageCode = "en-us"
title = "Anjali Bapat Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true 
disableSitemap = true
disable404 = true

[params] 

# Meta
    description = "Website with hugo-orbit-theme"
    author = "Anjali Bapat"
 
# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # itâ€™s quick and easy to change the styling and colour scheme.

    styles = "styles-5.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Anjali Bapat"
        tagline = "Data Science Masters student"
        avatar = "Anjali.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: abapat5@uncc.edu"
        title = "abapat5@uncc.edu"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+9807774212"
        title = "+19807774212"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/anjali-bapat-data-science-visualization-analytics"
        title = "linkedin.com/in/Anjali-Bapat"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/anjbapat"
        title = "github.com/anjbapat"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/bapat_anjali?lang=en"
        title = "@bapat_anjali"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Masters in Data Science and Business Analytics"
        college = "University of North Carolina, Charlotte"
        dates = "2019 - 2020"

        [[params.education.list]]
        degree = "Bachelor of Engineering in Electronics and Communication"
        college = "Mahakal Institute of Technology & Science, Ujjain, M.P. India"
        dates = "2008 - 2012"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Hindi"
        level = "Native"

        [[params.language.list]]
        language = "Marathi"
        level = "Native" 

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Painting"

        [[params.interests.list]]
        interest = "Watching Movies"

        [[params.interests.list]]
        interest = "Trekking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "To obtain an internship in Spring 2020(available from January 2020) as Data Scientist utilizing my strong analytical and strategical thinking skills to help making business decisions and help industries gain competitive advantage."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Technical Services Specialist"
        dates = "Dec 2017 - Jan 2019"
        company = "IBM India private limited, Hyderabad, India"
        details = "Managing and supporting Lync 2010 and Lync 2013 Unified communications Enterprise Environment providing voice and video over IP, Instant messaging, Presence, Web conferencing for users across the globe. Building enterprise voice sites with normalization rules, voice routes, Trunk configuration, voice policies, PSTN Usages to successfully call PSTN numbers through Lync. Using PowerShell scripting to modify the rules."

        [[params.jobs.list]]
        position = "Technical Consultant"
        dates = "June 2013- Dec 2017"
        company = "Wipro Ltd. Belapur, Navi. Mumbai, India"
        details = "Worked as a Microsoft front line engineer for Skype for Business (Lync) supporting user trouble ticking and some server tickets.Supported on issues related to S4B and Exchange Integration. Configured Hybrid setup for Skype for Business between On-premises and O365."


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        
        [[params.projects.list]]
        title = "Shiny app to explore William Shakespeare's plays in Rstudio"
        url = "https://anjali-bapat.shinyapps.io/Problemset3/"
        tagline = "Shiny app in R studio to explore three of William Shakespeare's plays namely-A Mid Summer Night's Dream,The Merchant of Venice,Romeo and Juliet, through simple data visualizations."

        [[params.projects.list]]
        title = "Fuel Economy Analysis through R"
        url = "https://anjali-bapat.shinyapps.io/FuelEconomyAnalysis/"
        tagline = "Shiny Enabled flexdashboard in R to analyse the fuel economy changes in US from 1984-2015."


        
    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "SAS"
        level = "70%"
                
        [[params.skills.list]]
        skill = "C & C++"
        level = "80%"

        [[params.skills.list]]
        skill = "MySQL"
        level = "80%"

        [[params.skills.list]]
        skill = "R and RShiny"
        level = "50%"

        [[params.skills.list]]
        skill = "Tableau"
        level = "65%"

        [[params.skills.list]]
        skill = "Relational database"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Created by Anjali Bapat"
